### ISSUE TITLE
Downloading related images produces incorrect directory syntax

### ISSUE THREAD

**Issue by 4OH4** [hardikvasa/google-images-download#214]
When downloading with the --related-images parameter, the downloader tries to create a directory with an invalid name and crashes.

For example (Windows 10, Python 3.6):
`python google_images_download.py -k "disc brake" -l 10 -ri `

...produces:
`Item no.: 1 --> Item name = disc brake`
`Evaluating...`
`Starting Download...`
`Completed Image ====> 1. 1200px-disk_brake_dsc03682.jpg`
`Completed Image ====> 2. 1175-front.jpg`
`...`
`Completed Image ====> 10. car-disc-brake-cluster.jpg`

`Getting list of related keywords...this may take a few moments`

`Now Downloading - disc brake - disc+brake,g_1:motorcycle:SsiXX7r2me8%3D&amp;usg=AI4_-kQTz_e6pgr8yN7IAZTX6buWsweNYg&amp;sa=X&amp;ved=0ahUKEwjC-_Hw0f_gAhWRonEKHYzLB1kQ4lYIKCgB`

`OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'downloads\\disc brake - disc+brake,g_1:motorcycle:SsiXX7r2me8%3D&amp;usg=AI4_-kQTz_e6pgr8yN7IAZTX6buWsweNYg&amp;sa=X&amp;ved=0ahUKEwjC-_Hw0f_gAhWRonEKHYzLB1kQ4lYIKCgB'`

The `create_directories()` function is trying to create a directory that contains invalid characters, or sometimes the directory path is too long.

I think the problem arises because at the end of the `download()` function, it calls `get_all_tabs()` and extracts `item_name` which becomes appended to the path. I can probably fix this and submit a pull request, although am a bit unsure what the desired behaviour should be, so any suggestions welcome.

**Comment by captainantilles** [comment]
I second this finding. Would it make sense to implement the function, so that it creates a forthrunning directory structure? ie. 1,2,3,4 etc for each related image? I have not checked the output that it supposed to generate. The error also happening for a single word, ie: googleimagesdownload -k "paris" -l 5 -ri

**Comment by hardikvasa** [comment]
@4OH4 @captainantilles this was recently fixed in #177 . Can you confirm if new version of this lib resolves the issue for you?

**Comment by captainantilles** [comment]
googleimagesdownload -k "paris" -l 5 -ri produces "ValueError: stat: path too long for Windows" as an error still. I tried to update via pip, not sure if that gives me the correct version with the fix included. Is there a command to verify the build/version?

**Comment by hardikvasa** [comment]
@captainantilles 
you can upgrade the library with the command
`pip install google-images-download --upgrade`

then you can use the following command to verify the version
`pip freeze | grep google-images-download`

let me know if version 2.6.1 still gives you this issue...

**Comment by captainantilles** [comment]
@hardikvasa I still have the problem. the package is up to date. Please see the log og the commands below. 

`C:\Temp>pip install google-images-download --upgrade
Requirement already up-to-date: google-images-download in c:\users\milterm\appdata\local\programs\python\python37-32\lib\site-packages (2.6.1)
Requirement already satisfied, skipping upgrade: selenium in c:\users\milterm\appdata\local\programs\python\python37-32\lib\site-packages (from google-images-download) (3.141.0)
Requirement already satisfied, skipping upgrade: urllib3 in c:\users\milterm\appdata\local\programs\python\python37-32\lib\site-packages (from selenium->google-images-download) (1.24.1)

C:\Temp>pip freeze
asn1crypto==0.24.0
beautifulsoup4==4.7.1
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
cryptography==2.6.1
ffmpeg==1.4
google-images-download==2.6.1
idna==2.8
lxml==4.3.3
pycparser==2.19
pyOpenSSL==19.0.0
requests==2.21.0
selenium==3.141.0
six==1.12.0
soupsieve==1.9.1
urllib3==1.24.1
youtube-dl==2019.4.24

C:\Temp>googleimagesdownload -k "paris" -l 5 -ri

Item no.: 1 --> Item name = paris
Evaluating...
Starting Download...
Completed Image ====> 1. paris-2017-home?wid=2880&hei=1280&fmt=jpeg&crop=9,336,2699,1200&anchor=1358,936&qlt=75,0&fit=wrap&op_sharpen=0&resMode=sharp2&op_usm=0,0,0,0&iccEmbed=0&printRes=72.jpg
Completed Image ====> 2. paris-cityscape-overview-guide.jpg
Completed Image ====> 3. a330628091ede7eb1548d6cda58e0357.jpg
Completed Image ====> 4. @david_fossa-2.jpg
Completed Image ====> 5. 15_HI_Paris_Eiffeltaarnet_6.jpg

Getting list of related keywords...this may take a few moments

Now Downloading - paris - paris places&sa=X&ved=0ahUKEwiyquTduYbiAhWNaVAKHSxHB2MQ4lYIKSgD">
Traceback (most recent call last):
  File "C:\Users\milterm\AppData\Local\Programs\Python\Python37-32\Scripts\googleimagesdownload-script.py", line 11, in <module>
    load_entry_point('google-images-download==2.6.1', 'console_scripts', 'googleimagesdownload')()
  File "c:\users\milterm\appdata\local\programs\python\python37-32\lib\site-packages\google_images_download\google_images_download.py", line 922, in main
    paths = response.download(arguments)  #wrapping response in a variable just for consistency
  File "c:\users\milterm\appdata\local\programs\python\python37-32\lib\site-packages\google_images_download\google_images_download.py", line 902, in download
    self.create_directories(main_directory, final_search_term,arguments['thumbnail'])
  File "c:\users\milterm\appdata\local\programs\python\python37-32\lib\site-packages\google_images_download\google_images_download.py", line 487, in create_directories
    if not os.path.exists(sub_directory):
  File "c:\users\milterm\appdata\local\programs\python\python37-32\lib\genericpath.py", line 19, in exists
    os.stat(path)
ValueError: stat: path too long for Windows

C:\Temp>`

**Comment by captainantilles** [comment]
@hardikvasa See the full log here: [https://www.dropbox.com/s/agfovamiw0s42f3/output.log?dl=0](url)

**Comment by hardikvasa** [comment]
@captainantilles the original issue was fixed in #177 . What you are referring to is a new bug that was caused due to some changes in the source pages retrieved. Tracking it in #234 . Closing out this one.
